version: "3.9"

services:
  documentary:

    container_name: before-her-name-existed

    build:
      context: .
      dockerfile: Dockerfile

    restart: always

    ports:
      - "3000:3000"

    environment:
      NODE_ENV: production

    networks:
      - documentary-network

networks:
  documentary-network: